<?php

return [
    'taxcodes' => [
        'code' => 'IMSET',
        'type' => 'SST',
        'description' => 'Imported Service Tax',
        'category' => 'IMSET',
        'rate' => 6.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'IMSETE',
        'type' => 'SST',
        'description' => 'Imported Service Tax (Exempted)',
        'category' => 'IMSETE',
        'rate' => 6.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'PEC1',
        'type' => 'SST',
        'description' => 'Purchases exempted according to Schedule C - Item 1',
        'category' => 'PEC1',
        'rate' => 0.00,
        'transaction_type' => 'purchase',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'PEC2',
        'type' => 'SST',
        'description' => 'Purchases exempted according to Schedule C - Item 2',
        'category' => 'PEC2',
        'rate' => 0.00,
        'transaction_type' => 'purchase',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'PEC3',
        'type' => 'SST',
        'description' => 'Purchases exempted according to Schedule C - Item 3',
        'category' => 'PEC3',
        'rate' => 0.00,
        'transaction_type' => 'purchase',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'PEC4',
        'type' => 'SST',
        'description' => 'Purchases exempted according to Schedule C - Item 4',
        'category' => 'PEC4',
        'rate' => 0.00,
        'transaction_type' => 'purchase',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'PEC5',
        'type' => 'SST',
        'description' => 'Purchases exempted according to Schedule C - Item 5',
        'category' => 'PEC5',
        'rate' => 0.00,
        'transaction_type' => 'purchase',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SAT05',
        'type' => 'SST',
        'description' => 'Sales Tax @ 5%',
        'category' => 'SAT05',
        'rate' => 5.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SAT10',
        'type' => 'SST',
        'description' => 'Sales Tax @ 10%',
        'category' => 'SAT10',
        'rate' => 10.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SATO05',
        'type' => 'SST',
        'description' => 'Sales Tax @ 5% (Own Used/Disposed)',
        'category' => 'SATO05',
        'rate' => 5.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SATO10',
        'type' => 'SST',
        'description' => 'Sales Tax @ 10% (Own Used/Disposed)',
        'category' => 'SATO10',
        'rate' => 10.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SEA',
        'type' => 'SST',
        'description' => 'Local Sales exempted according to Schedule A (Class of Person)',
        'category' => 'SEA',
        'rate' => 0.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SEB',
        'type' => 'SST',
        'description' => 'Local Sales exempted according to Schedule B (Manufacturer of specific non taxable goods)',
        'category' => 'SEB',
        'rate' => 0.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SEC1',
        'type' => 'SST',
        'description' => 'Local Sales exempted according to Schedule C - Item 1',
        'category' => 'SEC1',
        'rate' => 0.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SEC2',
        'type' => 'SST',
        'description' => 'Local Sales exempted according to Schedule C - Item 2',
        'category' => 'SEC2',
        'rate' => 0.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SEC3',
        'type' => 'SST',
        'description' => 'Local Sales exempted according to Schedule C - Item 3',
        'category' => 'SEC3',
        'rate' => 0.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SEC4',
        'type' => 'SST',
        'description' => 'Local Sales exempted according to Schedule C - Item 4',
        'category' => 'SEC4',
        'rate' => 0.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SEC5',
        'type' => 'SST',
        'description' => 'Local Sales exempted according to Schedule C - Item 5',
        'category' => 'SEC5',
        'rate' => 0.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SET',
        'type' => 'SST',
        'description' => 'Service Tax',
        'category' => 'SET',
        'rate' => 6.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SETE',
        'type' => 'SST',
        'description' => 'Service Tax (Exempted)',
        'category' => 'SETE',
        'rate' => 6.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SETO',
        'type' => 'SST',
        'description' => 'Service Tax (Own Used/Disposed)',
        'category' => 'SETO',
        'rate' => 6.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
    [
        'code' => 'SSA',
        'type' => 'SST',
        'description' => 'Export/Special Area/Designated Area',
        'category' => 'SSA',
        'rate' => 0.00,
        'transaction_type' => 'sales',
        'tariff_code'=> NULL,
    ],
];